name: Build xformers wheel on Power

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: string
  workflow_call:
    inputs:
      release:
        required: true
        type: string

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/ppc64le"

      - name: Install
        id: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          docker run --rm --platform "linux/ppc64le" -e VERSION="${{ inputs.release }}"
          --mount "type=bind,src=$(pwd),dst=/build"
          -w "/build" ppc64le/almalinux /bin/bash -ec '
          export PATH="/root/micromamba/bin:/opt/rh/gcc-toolset-12/root/usr/bin:/usr/local/cargo/bin:$PATH";
          dnf update -y;
          dnf group install -y "Development Tools";
          dnf install --allowerasing -y git wget curl vim gcc-toolset-12 bzip2;

          curl -Ls https://micro.mamba.pm/api/micromamba/linux-ppc64le/latest | tar -xvj bin/micromamba && mv bin/micromamba /usr/bin/;

          micromamba install -y --root-prefix=~/micromamba --prefix=~/micromamba -c rocketce -c defaults python=3.11 numpy httptools && micromamba clean --all --yes;
          
          git clone https://github.com/facebookresearch/xformers.git && cd xformers;
          git submodule update --init --recursive;

          python -m pip install -v --prefer-binary --extra-index-url https://repo.fury.io/mgiessing \
            "cmake>=3.26" ninja packaging "setuptools-scm>=8" setuptools wheel jinja2 \
            torch==2.4.0 \
            uvloop==0.20.0;
          
          python -m pip wheel --prefer-binary --extra-index-url https://repo.fury.io/mgiessing .;

          WHEEL_PATH=$(find / -name "xformers*.whl" | head -1);
          cp $WHEEL_PATH /build/xformers-$VERSION-cp311-cp311-linux_ppc64le.whl;'          

      - name: Create a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git tag ${{ inputs.release }}
          git push origin ${{ inputs.release }} -f

      - name: Capture the file
        id: capture
        run: |
          WHEEL_PATH=$(find $PWD -name "xformers*.whl" -maxdepth 1)
          echo "Found $WHEEL_PATH"
          echo "ARTIFACT=$WHEEL_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.release }}
          tag_name: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.capture.outputs.ARTIFACT }}
          draft: false
          prerelease: false
