name: Check for new xformers release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest

    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq

      - name: Get latest xformers release
        id: latest
        run: |
          XFORMERS_LATEST=$(curl -s https://pypi.org/pypi/xformers/json | jq -r '.info.version')
          echo "LATEST_RELEASE=$XFORMERS_LATEST" >> $GITHUB_OUTPUT
          echo "Latest xformers version: "$XFORMERS_LATEST

      - name: Get current xformers release for Power
        id: current
        run: |
          XFORMERS_CURRENT=$(curl -s https://api.github.com/repos/DahlitzFlorian/xformers-ppc64le/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "CURRENT_RELEASE=$XFORMERS_CURRENT" >> $GITHUB_OUTPUT
          echo "Current xformers version on Power: "$XFORMERS_CURRENT

  build-new-release:
    needs: [check-release]
    if: needs.check-release.outputs.latest-release != needs.check-release.outputs.current-release
    uses: ./.github/workflows/build_xformers.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
